### PR TITLE
Added followPlaceholder option

### PR DESCRIPTION
**Pull request by cgvedant**
This lets us ignore the value of placeholder after mounting the component. Useful when we use redux along with this component.

### CODE REVIEW

**Comment by Patrick-Sachs** [comment]
First of all thanks for the contribution and active discussions in the recent days!

However, I'm not sure if this is something that should be handled by this component as this looks like a specific use case. 

Wouldn't it be possible to solve this in the component embedding the react-json-editor-ajrm by not passing updated `placeholder` values to this component? Or is this not really possible with Redux? (I don't use Redux so I do not have experience in it)

---

@AndrewRedican Sorry for using multiple accounts from time to time, I'm currently working on being able to use my private @PatrickSachs account at work, which would simplify a lot of git related things.

**Comment by cgvedant** [comment]
This is not only redux specific but also helps when placeholder is same as the state influenced by onChange [example](https://github.com/AndrewRedican/react-json-editor-ajrm/issues/64).
It is possible to store a frozen object that would be passed onto the placeholder, but it just acts as an unnecessary wrapper. I feel this functionality fits well within RJEA and it also helps make the component more efficient when we are sure we want the placeholder to be used only on mount.

**Comment by Patrick-Sachs** [comment]
I see now. The argument that would be an unnecessary wrapper does make sense. Thank you for your quick reply.

**Comment by AndrewRedican** [comment]
Hi @cgvedant,

I don't dislike the idea. However, I think that a change in `placeholder` value should always trigger a re-render, always. Adding a property to 'lock' to prevent a re-render is a bit ackward, goes against the usual react pattern.

On the other hand, I agree we wouldn't want to trigger a re-render whenever a new `placeholder` value differs from the current value of the content displayed. This should be an opt-in feature.

In this regards, I will still give you credit for your feedback/contribution.

**Pull request closed without merging**
