### PR TITLE
Locale japanese

### PR DESCRIPTION
**Pull request by Adityaperiwal**

### CODE REVIEW

**Comment by PatrickSachs** [comment]
There are several occasions in which there are no spaces in between the placeholders and the rest of the translated string. I don't speak a single word of Japanese, so I'm rather confused. Are spaces something you can omit in the language?

**Comment by Adityaperiwal** [comment]
Actually Japanese is written with characters that don't require spaces,  its like it takes words and compacts them into unique consecutive pattern of letters without using any spaces. So, its rather a pattern specific language.

**Comment by PatrickSachs** [comment]
Got it, thank you!

**Comment by PatrickSachs** [comment]
Thank you very much for this translation!

**Pull request merged**
