### PR TITLE
Support ru

### PR DESCRIPTION
**Pull request by askesis**
Created Russian translation in `ru.js `

### CODE REVIEW

**Comment by AndrewRedican** [comment]
@Hey askesis.

Thanks for your contribution.

**Comment by askesis** [comment]
Hey, @AndrewRedican :)

PR has a not clear name, this is not problem? I just didn't notice this

**Comment by AndrewRedican** [comment]
That's okay. I will be merging shortly.

**Comment by askesis** [comment]
Thanks!

**Pull request merged**
