### PR TITLE
Implemented Locale System

### PR DESCRIPTION
**Pull request by PatrickSachs**
Addresses #23 

This PR implements a locale system, allowing users to translate all messages in the react-json-editor-ajrm to their language. By moving each locale into a separate file only the locales actually used will be included in the build.

How to use?
```jsx
import JSONInput from 'react-json-editor-ajrm'; 
import locale from 'react-json-editor-ajrm/locale/en';

<JSONInput
    id = 'unique_string'
    placeholder = {sampleData}
    theme = 'light_mitsuketa_tribute'
    locale = {locale} // Locale included here
/>
```

How does a locale look like?
```js
module.exports = {
  format: "{reason} at line {line}",
  invalidToken: {
    sequence: "'{firstToken}' token cannot be followed by a '{secondToken}' token",
    double: "'{token}' token cannot be followed by another '{token}' token",
    whitelist: "'{firstToken}' token can only follow '{secondToken}' token",
    useInstead: "'{badToken}' token is not accepted. Use '{goodToken}' instead",
    unexpected: "Unexpected '{token}' token found"
  },
  // ...
};
```

Is this a breaking change? **Yes** - The `locale` prop is required. I did not add the english language as default since this would include the english locale in the users build regardless of if it's used or not.

Potential problems? **Maybe** - I am unsure if the import will actually work with `'react-json-editor-ajrm/locale/en'` it is possible that additional configuration in the package.json has to be made in order to allow this. I was only able to test import using the source code and not the NPM module locally.

Workflow changes? **No** - Although I introduced a new webpack plugin to the build pipeline. If there is a better way to achieve the build output feel free to change this. I am by no means a webpack expert 🙃

### CODE REVIEW

**Comment by AndrewRedican** [comment]
Hey @PatrickSachs,

1. I've reviewed your `locale system` update and it looks great. Also learned a few things.
2. I've also tested updated distribution version and it works properly. 3. Fixed this [issue](https://github.com/AndrewRedican/react-json-editor-ajrm/issues/17) in the process.
I also added spanish localization support.

==============

While adding localization support, I realized some of the locale modules structure needs to be made more granular. See my comments inside `locale/es`.

The following `reason` templates must be split into two cases each.
```
brace.cannotWrap
string.missingOpen
string.missingClose
```
The problem is, the way is set up, compound words, are not considered as single units.

In english, we can simply replace one word to change the meaning of the compound word. For example; `single quotes` and `double quotes`, or `braces and curly braces`. While we can keep the second word, in some languages such as spanish each might different. In spanish `braces and curly braces` are `corchetes y llavas`.

Can you help me edit it the local structure to account for these details? If you edit `locale/de` to give me a reference, I can update `locale/en` and `local/es` accordingly.

==============

On a separate subject, I would really like to provide default language whenever the user does not specify one. I would think english would be the best pick for a default language should no locale property is provided, even if we need to add it directly into component. That is the only solution I can think of, I am open to suggestions.

==============

I've was able to import component and locale files unsing ES6 syntax separately with the current setup in the `/dist` folder, using the example project. I am also not entirely sure if we can add something else like a index.js / package.json to increase for other projects to be able to import though.

==============

Before merging to master, and after address the concerns above, I'd like to include information about contributors and add a proper change log too.

*Self reminder: Update documentation, package versions, and run tests prior release.

**Comment by PatrickSachs** [comment]
Thanks for the review @AndrewRedican!

==============

> While adding localization support, I realized some of the locale modules' structure needs to be made more granular. See my comments inside locale/es. [...]

I was almost afraid that we'd run into issues with localization sooner or later given the rather simplistic nature of the system. Seems like we'll have them right away. 😄 

Just making sure I'm getting the problem right: The issue is that separate `reason` templates are required for both curly braces are square braces?

Would changing the `brace` locale to this format help?
```js
brace: {
  curly: {
    missingOpen: "Missing '{' open curly brace",
    missingClose: "Open '{open}' curly brace is missing closing '{close}' curly brace",
    cannotWrap: "'{token}' token cannot be wrapped in '{brace}' curly braces"
  },
  square: { 
    missingOpen: "Missing '[' open square brace", 
    missingClose: "Open '{open}' square brace is missing closing '{close}' square brace",
    cannotWrap: "'{token}' token cannot be wrapped in '{brace}' square braces"
  }
}
```

==============

> On a separate subject, I would really like to provide a one default language whenever the user does not specify one. [...]

I can fully understand that. Setting english as default language would also make this a non breaking change since users would not have to change their props.
I can't think of a way to include the locale "lazily" that would not require users to use code splitting, so I suppose we'll just have to live with having potentially ~2KB of unused code in the bundle. I think that's ok for now.

==============

> I was able to import component and locale files unsing ES6 syntax separately with the current setup in the /dist folder, using the example project. I am also not entirely sure if we can add something else like a index.js / package.json to increase import/require compatability for other projects.

I can't completely follow you here - I'm really sorry. Is there an issue with the package.json?

==============

> Before merging to master, and after address the concerns above, I'd like to include information about contributors and add a proper change log too.

Sounds good to me!

**Comment by AndrewRedican** [comment]
> Just making sure I'm getting the problem right: The issue is that separate `reason` templates are required for both curly braces are square braces?

Sorry I couldn't explain myself clearly. Yes, that is correct! We'll also need something for:
```
string.missingOpen
string.missingClose
```

> Would changing the brace locale to this format help?

That will work perfectly.

> I can't think of a way to include the locale "lazily" that would not require users to use code splitting, so I suppose we'll just have to live with having potentially ~2KB of unused code in the bundle. I think that's ok for now.

We should update document as if it is `locale` property is **required**. We can temporarily provide a default `locale/en` in component if no `locale` is not provided *with* a warning message advising to add it, and that it is scheduled to be required by a specfic version, say `2.5.5`. Let me know if you agree and/or want me to take care of this.

> I can't completely follow you here - I'm really sorry. Is there an issue with the package.json?

That's alright. I tested import / require statements with the our internal example project. I didn't find any issue importing `locale` files or component's index from the distribution version (yet). 
I was merely stating that I was not entirely sure we would need to set up additional webpack configuration to bundle `locale` files for other project setups.

**Comment by PatrickSachs** [comment]
Alright!

I updated the locale templates, they should be ready for translation.

> We can temporarily provide a default locale/en in component if no locale is not provided with a warning message advising to add it [...]

The english locale has been set as default. I really like your approach - provide a non breaking solution for now, prepare the users for it, and wait until there is another breaking change "worth breaking for" to follow through with it. 👍 

> We should update documentation as if ithe locale property is required. [...]

I also added some basic explanation of the locale to the documentation, but I kept it rather short as I didn't want to make changes to your README/"front page" that aren't fully within your vision of how you want to present your project.

> I was merely stating that I was not entirely sure we would need to set up additional webpack configuration to bundle locale files for other project setups.

Feel free to change around the webpack configuration however you think is best for this project/you prefer. I'm not the greatest with setting up webpack/build systems so I may have setup something unnecessarily complex/unneeded.

> Before merging to master, and after address the concerns above, I'd like to include information about contributors and add a proper change log too.

Is there a template on how you want your changelogs to look like, or do you want to write the changelog/contributors part?

**Comment by PatrickSachs** [comment]
Just skimmed through the commit: I totally forgot the differentiation between the single and double quote strings. It looks like you were able to translate it regardless though? Should we go back and add this?

**Comment by AndrewRedican** [comment]
I was able to translate it without a problem. I think we are good for now.

**Pull request merged**
