### PR TITLE
Add @babel/runtime as a dependency

### LINKED ISSUE #37: Importing component display error on different set up
1. What version of RJEA are you using (react-json-editor-ajrm version)? `2.5.2`
2. What operating system and processor architecture are you using? `Windows 10`
3. What did you do? Import component according to instructions.
4. What did you expect to see? No errors on import.
5. What did you see instead?

This errors occurs for either normal or `es` import.
I am using a different working setup (than the one provided in this repo).
The setup I am using includes webpack 3 and babel 6.

image

### PR DESCRIPTION
**Pull request by PatrickSachs**
Fixes #37 

Tested in a webpack 4 & babel 6 setup, compiled without any issues.

I also went ahead and updated the babel versions while we are at it since beta -> rc was a breaking change for babel. We are not affected by the effects of this.

### CODE REVIEW

**Comment by AndrewRedican** [comment]
Hey @PatrickSachs,

I am try to import this component to my babel 6 webpack 3, set up, its requesting me the following:
@babel/runtime/core-js/json/stringify
@babel/runtime/core-js/object/keys
@babel/runtime/helpers/es6/objectSpread

To test this without actually publishing, I:
1. Ran: ```npm run test:release```
2. Copied contents of `dist/` into the other repositories' node_modules/react-json-editor-ajrm
3. Manually imported @babel/runtime

Then I started test deployment, and I see this:

I thought it was because I was using `/es` version. Switched to normal input, same results.

image

**Comment by Patrick-Sachs** [comment]
> Ran: npm run test:release

This command should output a react-json-editor-ajrm-major.minor.patch.tgz file.

> Copied contents of dist/ into the other repositories' node_modules/react-json-editor-ajrm

Go into the other repository and run `npm i ./path/to/react-json-editor-ajrm-major.minor.patch.tgz`

This will install the .tgz file created by the previous output as if it were installed from npm.

> Ran npm i @babel/runtime

Users do not need to manually install `@babel/runtime`, it is a dependency of react-json-editor-ajrm. They can do so if they want, but do not have to(!).

I'll look into trying this with webpack 3 once I get home today, only tried with webpack 4 so far. If its not compatible with webpack 3 this approach is obviously not an option.

**Comment by PatrickSachs** [comment]
I was not able to reproduce the error with webpack 3 and babel 6(Both using babel-loader 6 and 7).

If it's still not working out for you I can do a screen recording and we can check were our workflow differs/problems may come from.

**Comment by AndrewRedican** [comment]
Hey @PatrickSachs,

Sorry I couldn't get back to you sooner.

> Maybe delete your react-json-editor-ajrm/node_modules folder and package-lock.json once before running test:release, just for the sake of this test to make sure that nothing strange is cached. :

This worked 🎉 . On my local project setup, I deleted `package-lock.json` and `node_modules`, reinstalled again `npm i`, then ran `test:release` according to instructions.  After adding the `dist/` contents to the `node_modules/react-json-editor-ajrm` again to the webpack-3 babel-6 project setup (with `@babel/runtime` already installed) finally worked this time. 

I wonder how this `cache` issue ocurrs and if there is a to prevent it, especially considering I could have published a release with this problem unkowingly and give us a hard time figuring out the problem later.

I would suggest automatically deleting `node_modules` and `package-lock.json` and running `npm i` prior to `build` on `npm run release`. Do you think this is over the top, or is there a better way to prevent the cache issue?

**Comment by Patrick-Sachs** [comment]
I am not 100% sure what caused the cache issue. It may be simply that we updated a package (@babel/runtime) to a new major version and npm didn't quite catch up to that. 

From what I read about the funcaionality of package-lock.json, deleting it every time we make builds seems like it's not the way to go: https://medium.com/@Quigley_Ja/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8 - Let's see if this issue ever crops up again

Looks good to me too, we can merge this branch.

**Pull request merged**
