### PR TITLE
Use Babel for builds

### PR DESCRIPTION
**Pull request by PatrickSachs**
Webpack is meant for the final bundling of a code base. Libraries are better built using raw Babel. 

- Allows us to scale better as the project grows in size
- Allows us to provide a version with polyfills etc already included
- Allows the user to use their own module bundler/polyfills/etc... if they want to

See #31 for details & discussion.

### CODE REVIEW

**Comment by AndrewRedican** [comment]
Okay, we'll need to update tests.

**Comment by AndrewRedican** [comment]
Found a possible solution to item 1 here https://github.com/facebook/jest/issues/1468#issuecomment-276753756.

**Comment by PatrickSachs** [comment]
> Apparently Jest only uses .babelrc, so I am reinstating that file (with updated babel 7 transforms).

Interestingly when googling around I found some tickets from people who had the opposite problem: Their .babelrc not being read, so they had to use babel.config.js instead.

Anyways, I don't think that we can use .babe.rc since it's just a JSON file. Our setup determines the different presets, etc. to use programmatically at build time using the JavaScript in babel.config.js.

> This is no longer valid [...] `import Enzyme, { shallow, render, mount } from 'enzyme';`

Looking at the Enzyme type definition, it doesn't look like Enzyme actually has a default export. Does using `import { configure, shallow, render, mount } from 'enzyme';` or `import * as Enzyme from 'enzyme';` fix the issue?

**Comment by AndrewRedican** [comment]
The warnings don't make sure sense either. Notice how its pointing at comments, and or space or tabs.

image


image

image

**Comment by AndrewRedican** [comment]
I am fairly new to `jest`. I am up for trying a bit more, worst case scenario, look for a different testing framework that we can use with react component or focus test on tokenize() and other parsing functions for expect results.

**Comment by AndrewRedican** [comment]
I fixed the issue. I will update shortly

**Comment by AndrewRedican** [comment]
Setting useESModules to `false` fixed the issue import / export issues on test. See [useesmodules](https://babeljs.io/docs/en/next/babel-plugin-transform-runtime.html#useesmodules)

**Comment by PatrickSachs** [comment]
> Setting useESModules to false fixed the issue import / export issues on test. See useesmodules

This is awesome! With the transformer we are actually able to re-use our existing babel.config, allowing us to keep configuration babel in a single place.

**Comment by AndrewRedican** [comment]
I think we are good place now. Free free to add items to the CHANGELOG.md.
Let me know so I can merge.
I won't be publishing until I add a few tests and fix https://github.com/AndrewRedican/react-json-editor-ajrm/issues/32.

**Comment by PatrickSachs** [comment]
I'm ready to merge at this point.

**Pull request merged**
