### PR TITLE
Example/plain create react app example

### PR DESCRIPTION
**Pull request by PetrykowskiM**
## Description
I added a new example that shows the integration of this project within create-react-app.

This PR is a proposal for the problem that came up in [issue 51 ](https://github.com/AndrewRedican/react-json-editor-ajrm/issues/51)

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Thank you very much for this! Just tested it and it works flawlessly.

I'm a bit unsure about the create-react-app example using yarn since we use npm for everything else, but aside from that it looks perfect!

**Comment by AndrewRedican** [comment]
@PetrykowskiM, again, thanks for your contribution!

@PatrickSachs, this looks good to me. 

I don't mind the new example using yarn, to my understanding that is something commonly used for create-react-app examples as far as I know.  

I wanted to ask, how were you able to test changes of his w/o actually merging (I am still a noob at this). Were you able test the original example too?  If so, let's merge!

**Comment by PatrickSachs** [comment]
> I don't mind the new example using yarn, to my understanding that is something commonly used for create-react-app examples as far as I know.

True. I this case I agree.

> I wanted to ask, how were you able to test changes of his w/o actually merging (I am still a noob at this).

I cloned the fork and ran the example there. So my chain of commands was pretty much:

```bash
$ git clone https://github.com/PetrykowskiM/react-json-editor-ajrm
$ cd .\react-json-editor-ajrm\
$ git checkout plain-create-react-app-example
$ git pull
$ npm i
$ cd ./example/create-react-app
$ yarn (Or in my case I initially used npm i aswell before realizing the project uses yarn)
$ npm run start
```

> Were you able test the original example too? 

Yes. 

> If so, let's merge!

Awesome! Thanks  @PetrykowskiM for your contribution!

**Comment by AndrewRedican** [comment]
@PatrickSachs,

> I cloned the fork and ran the example there. So my chain of commands was pretty much [...]

Thanks mate. I'll do that next time.

I am merging now.

**Pull request merged**
