### PR TITLE
Make it possible to copy text when in viewOnly mode

### LINKED ISSUE #54: viewOnly set to true is preventing user from copy text
1. What version of RJEA are you using (react-json-editor-ajrm version)? 2.5.3
2. What operating system and processor architecture are you using? macOS
3. What did you do? trying to copy text with cmd + c
4. What did you expect to see? The text should be copied
5. What did you see instead? it wasn't.

I made a pr that would fix this. #53

### PR DESCRIPTION
**Pull request by rickbrunstedt**
When used as viewOnly mode, it is preventing the user from copy the text.

By checking if current event is a control- (for windows and linux? But correct me if I'm wrong) or meta-key (macOS), then do not run this.stopEvent.
Then the copy event can happen without preventDefault blocking it.

Fixes #54

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Thank you very much for this contribution @rickbrunstedt!

Unfortunately this still has a few problems: It allows all key combinations involving Ctrl to be used, including e.g. Ctrl + X to cut the text.

I was not able to test the behavior on macOS, how does it behave there?

**Comment by rickbrunstedt** [comment]
@PatrickSachs Hahah sorry that was a bit sloppy of me. 
Last commit should fix this problem. Maybe there is a better way of doing this that you know of? :)

**Comment by PatrickSachs** [comment]
> Maybe there is a better way of doing this that you know of? :)

Not one that I'd be aware of, no. But I think this solution should suffice for most use cases.

Now if the CTRL + A hotkey would also be allowed to select all content this would be perfect :)

**Comment by rickbrunstedt** [comment]
@PatrickSachs While I'm on it I thought I could allow the arrow keys as well, and have just made another commit.

Though I'm a bit unsure `this.setUpdateTime()` purpose is. Am I using at the right place?

As you can see in the most recent commit, I didn't handle shift, on mac it seems to work anyway. Could you confirm that on windows, otherwise I test it on a windows machine at work.

Please have a look at it give me some feedback.

**Comment by PatrickSachs** [comment]
> While I was on it I thought I could allow the arrow keys as well, and have just made another commit.

Awesome! 🎉

> Though I'm a bit unsure this.setUpdateTime() purpose is. Am I using it at the right place?

Calling `setUpdateTime` schedules an update(and thus also calling the `onChange` prop) for the component. If an update has already been scheduled the update will be re-scheduled and thus delayed.

Since updating the component also reformats the entire code this should be called whenever the user performs input to not mess up things while they type or select something.

For normal key presses this is called in `onKeyPress`, for some special keys we are doing this in `onKeyDown`.

> Am I using it at the right place?

Yes

> Could you confirm that on windows, otherwise I test it on a windows machine at work.

Works on Windows 10 and Ubuntu in Chrome. 

There seems to be an issue with Firefox(61.0.2) on both Windows & Ubuntu though since it handles the cancellation of the key events a little bit differently than chrome. Since the problem did already exist before your change I added some commits to your PR to fix this.

**Comment by rickbrunstedt** [comment]
Things seems to work great. I tried chrome, firefox and safari on macOS.

And thanks for this library, saved me a lot of time! :)

**Comment by PatrickSachs** [comment]
It will take a bit of time before this change will be published to NPM. If its possible you can install the project using a file dependency(`npm i path/to/react-json-editor-ajrm/dist`).

**Pull request merged**
