### PR TITLE
Fix onPaste returing error

### PR DESCRIPTION
**Pull request by sOoN92**
When pasting a JSON the component returns this error:

Non-alphanumeric token ' ' is not allowed outside string notation at line 1

I made a fix on onPaste method on line 571:
``` javascript
var text = event.clipboardData.getData('text/plain').replace(/(\r\n|\n|\r|\t|\u200B)/gm, '');
```
The replace added at the end of that line, remove the undesired characters causing the error.

### CODE REVIEW

**Comment by sOoN92** [comment]
@AndrewRedican do you still approve PR or follow this project? I can help you on this if you want.

**Comment by jlopvet** [comment]
@sOoN92 are you sure of your fix ? Tested on my side and still had the error.

**Comment by sOoN92** [comment]
@jlopvet I'm pretty sure, I don't have the error anymore. Can you share the test steps?

**Comment by jlopvet** [comment]
@sOoN92 changed line 636 to var text = event.clipboardData.getData('text/plain').replace(/(\r\n|\n|\r|\t)/gm, '');
Relaunched my dev server, pasted some json (with double quoted keys) and same error.

**Comment by sOoN92** [comment]
I updated the PR, can you check it again please @jlopvet ?

**Comment by oliverbock** [comment]
@sOoN92, it makes sense to me.

**Comment by raj-2011503554** [comment]
me too facing the same issue is the fix will be provided ??

**Pull request closed without merging**
