### PR TITLE
Added support to pt

### PR DESCRIPTION
**Pull request by AllanKDeveloper**
Hello Andrew,

I added support to pt language. But I am from Brazil, so I dont know if you want to add pt-br instead? It is your call.

Bests, Allan.

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Are these significantly differences from Brazilian Portuguese to non-Brazilian Portuguese? I'm asking since our languages are named by ISO 639-2 codes, which only has "pt" but no "pt-br"(unlike e.g. IETF language tags)

**Comment by AllanKDeveloper** [comment]
Actually some words are differently, but either Brazilian and Portuguese can understand the words.

**Comment by AndrewRedican** [comment]
Hey @AllanKDeveloper,

This is a great contribution. Thank you!

"pt" should suffice for now. We'll continue to use `iso639-2` until we have covered most of the broader scope of spoken/written languages, or until major interpretation problems arise and it becomes clear we need to be more specific.

In the event another contributor submits a different flavor for Portuguese, or any other language that we already support, we will review case by case to determine whether we should add it, and differenciate existing support.

**Comment by AndrewRedican** [comment]
Added @AllanKDeveloper as contributor, and updated change log respectively.
Also added missing information on existing contributions.

**Comment by AndrewRedican** [comment]
We'll wait a little before publishing changes to npm (a week or so).
I'd like to bundle it with collapsible nodes feature.

**Pull request merged**
