### PR TITLE
Adding Bahasa Indonesia Translation

### PR DESCRIPTION
**Pull request by radityasurya**
Adding Bahasa Indonesia Translation to `src/locale/id.js`

**Why**
- Indonesia has 261 Millions of People
- Bahasa Indonesia is ranked number 14 most used language around the globe
- My native language :D

Hope this is helpful 👍

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Hey @radityasurya 

That's awesome, thank you very much! 
I'm amazed at the amount of people submitting translations to this project.

**Comment by radityasurya** [comment]
@PatrickSachs thanks for approving my PR, yeah I am starting to learn how to contribute on open source project :D

**Comment by PatrickSachs** [comment]
That's great! Translations are an awesome way to get started on that.

Just as a recommendation: make sure that your commits are authored using your GitHub username. This will actually list you as a contributor to the project in the GitHub (See at the top of https://github.com/AndrewRedican/react-json-editor-ajrm/commit/8738f88e80e64ab8f2fbb08c4643bfb42a2548f6).

Currently your username is set up as `raditya`, you may want to change that to `radityaraditya`. 😎

**Comment by radityasurya** [comment]
@PatrickSachs oops I forgot to set my git config, should I change it and re commit it again?

Anyway, I'll check if I can add any more addition or help to the project :D

**Comment by PatrickSachs** [comment]
> oops I forgot to set my git config, should I change it and re commit it again?

It's already merged, so we won't be able to change this anymore without creating headaches for everyone. No worries though, we track everyone who contributed directly in the readme, so your contribution won't be forgotten 😃

> Anyway, I'll check if I can add any more addition or help to the project :D

Help is always appreciated!

**Comment by radityasurya** [comment]
@PatrickSachs so sorry for that, will improve in the future 👍

**Pull request merged**
