### PR TITLE
Core tests

### PR DESCRIPTION
**Pull request by AndrewRedican**
1. Added `mitsuketa` as dev dependency.
2. Additional babel config for tests: Removed strict mode to enable `err.js` which is used to generate custom error messages.
3. Added render tests assigning values to all available component properties.
4. Run basic render (or "snapshot") tests against both: `source code` version and `distribution` version.
5. Added first syntax logic tests. Still missing some more (slightly more complicated ones). See TODO comments on `test/test.js`. I also created a modular function for this syntax logic evalation, in which you define a single test, but it runs two distinct test cases; It evaluates syntax logic when it receives a javascript object, then evaluates syntax logic when it receives a dom node.
6. As a test byproduct, found and solved issue: https://github.com/AndrewRedican/react-json-editor-ajrm/commit/335c899b4df369e9f8b6a6e2fed3c496e51af3a6.
7. Also addressed this issue https://github.com/AndrewRedican/react-json-editor-ajrm/issues/29.

Let me know if you have any suggestions or improvements of your own. Otherwise, please merge. 😄

(As best practice, I will not be pushing directly to master, until I get an extra set of eyes to approve.) Not that I ever do silly mistakes 😉 

One thing I'd like to do before next realease is to set up npm scripts to run tests _after_ builds but _before_ npm publish. I also need to delete the `test/___snapshots___` folder prior to every test run. Every time the source code is update, it produces a different snapshot. The basic render tests will fail whenever an outdated snapshot is compared against the new one.

Let me know if you have time help me with this last part too. Otherwise, I can take care of it during the weekend.

Cheers.

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Before I look through the tests, etc: I strongly dislike adding /dist or any generated files to the repository. It blows up commits and makes reading through them rather painful.

For example trying to get a good diff to what changed in this branch is really hard. 

I could look through every single commit, save the one that updated dist, but then I'd only see a fraction of the changes, with some of it possibly being changed again in a later commit.

Or I could look at the "Files changed" tab, but then I'd have to wade through all the /dist files that changed. Not great either.

Furthermore it makes every commit look like a monumental addition. Assume I quickly fixed a small bug by changing this like of code

```js
if (isValidMarkup(markup)) throw new Error("Invalid Markup!");
```

to
```js
if (!isValidMarkup(markup)) throw new Error("Invalid Markup!");
```

I'd expect the commit to look something like this:

```patch
Subject: Fixed markup validation
 1 file changed, 1 insertion(+), 1 deletion(-)
- if (isValidMarkup(markup)) throw new Error("Invalid Markup!");
+ if (!isValidMarkup(markup)) throw new Error("Invalid Markup!");
```

instead what we'd get is:

```patch
Subject: Fixed markup validation
 17 files changed, 5721 insertions(+), 4831 deletions(-)
-_this.newSpan = _this.newSpan.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
-_this.renderErrorMessage = _this.renderErrorMessage.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
-_this.onScroll = _this.onScroll.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
-_this.showPlaceholder = _this.showPlaceholder.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
-_this.tokenize = _this.tokenize.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
-_this.onKeyPress = _this.onKeyPress.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
-_this.onKeyDown = _this.onKeyDown.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
- if (isValidMarkup(markup)) throw new Error("Invalid Markup!");
- [....] Thousands more
+_this.newSpan = _this.newSpan.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+_this.renderErrorMessage = _this.renderErrorMessage.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+_this.onScroll = _this.onScroll.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+_this.showPlaceholder = _this.showPlaceholder.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+_this.tokenize = _this.tokenize.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+_this.onKeyPress = _this.onKeyPress.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+_this.onKeyDown = _this.onKeyDown.bind((0, _assertThisInitialized2.default)((0, _assertThisInitialized2.default)(_this)));
+ if (!isValidMarkup(markup)) throw new Error("Invalid Markup!");
+ [....] Thousands more

```

Whoa! That must have been some seriously broken validation!

There are some more reasons not to include generated files in git, like potentially reversing commits less of a pain, and reducing merge conflicts if both branches have conflicting build outputs.

I see why you included the dist however, at the moment the tests run against the /dist version and the /src version. Is there a way to change this, that maybe the build system runs npm run build prior to testing? (Or with the latest commit it wouldn't have to run test at all, since test in run after build)

**Comment by AndrewRedican** [comment]
I see what you mean... I agree.
The reason why I removed `/dist` the gitignore is to allow travis ci see  these files in order to run all tests successully (including dist version). Perhaps we can update the `.travis.yml` to send some kind of additional parameters to let travis run *only* source code tests. That way there is no need to commit `/dist`.

**Comment by AndrewRedican** [comment]
1. `/dist` and `test/___snapshot___` is no longer included in commits.
2. Additional travis.yml configuration to run source code tests.
3. Local tests will include distribution builds.

**Comment by PatrickSachs** [comment]
I just looked into the tests some some, but it looks like we don't need to test against /dist at all. We use the same Babel compiler flags for compiling the tests(`BABEL_ENV=modules:commonjs`) than we use for compiling dist, meaning they are identical code.

Can I change the render tests to both run against /src?

**Comment by AndrewRedican** [comment]
Hey @PatrickSachs,

>[...] Can I change the render tests to both run against /src?

We can remove `dist/test`.

> About #63f7940facf546d7d9cb9abf9db0b2a79697df88: The tests run and pass for me even without this plugin. Why do we need to disable strict mode? What error did you run into?

The error I ran into is that `arguments` is not allowed.

You won't run into this error until until a you use the small `err` framework I added. It depeneds on `arguments` to get information about the function its running in, to create a custom error message that mentions in which function this error ocurred. Unfortunately use of `arguments` is not allowed in strict mode. You can try this (without the remove strict flag) as an example:

```
   var testVar = 'hello world';
   err.isNotType(arguments,'testVar',testVar,'number');

   //this function will notice this testVar is not what was expected
   //and will throw a custom err, using information from arguments
```

I use this as means to provide early warning when required parameters for a function are not satisfied or incorrect. I usually add `err` statements at the top of before function begins. I also use it inside react component constructors, again, to provide an early error (less criptic) than an error found while performing other operations with incorrect parameters.

If you think this is an overkill or having remove-strict to much of an inconvenient we can remove.

**Pull request merged**
