### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by JustFly1984**
I've updated everything, installed eslint, and fixed all eslint warnings/errors. I made sure I passed all the tests. Updated examples. added propTypes. Made id prop required.

Enjoy.

### CODE REVIEW

**Comment by PatrickSachs** [comment]
Hey @JustFly1984 -

- First of all: This is awesome. 🎉 ESLint is something I've thought about for a longer time, but never found time to properly look at for this project. So absolute thumbs up for this one! 👍

- I see you also moved the logic into separate functions outside of the component. This is really neat because the logic for this was in my opinion sometimes hard to understand. So pushing for a more functional approach is definitely a step in the right direction as far as I'm concerned.

- I've never worked with PropTypes myself so I cannot say anything about them. Not sure about the ID being required again since we actively worked towards making it optional.

My only problem with this PR is it's huge size. Every one these three aforementioned bullet would be a rather large and independent PR of its own.

But regardless **huge props** to you for this, this will improve code quality a lot!

@AndrewRedican what's your take on this? 
ESLint will greatly help out with getting a consistent style across the project. Do you think this should be merged as-is or split into separate PRs and merged individually(Or potentially exclude one of the three changes something)?

**Comment by JustFly1984** [comment]
I did check all the tests, it is working. You can merge it as single commit, but you need to fix docs about ID being required. If you have more than one JSONInput on the page, it will cause accessibility issues if there is no id provided. PropTypes very important, cos they warn you in console if incorrect props passed down or required props is missing.

**Comment by JustFly1984** [comment]
The thing is - after I installed ESlint and run it for first time, it was 2200+ warnings/errors.
After running `npx eslint ./src --fix` there was 273 errors left.

I just started to fix everything while running tests in watch mode, until everything was fixed.

**Comment by JustFly1984** [comment]
Yesterday we decided to use `react-json-editor-ajrm` in our project, so I decided to look inside, and I've seen that issue about eslint and stuff, and decided to improve it as much as I can in single go.

**Comment by PatrickSachs** [comment]
> The thing is - after I installed ESlint and run it for first time, it was 2200+ warnings/errors.
After running npx eslint ./src --fix there was 273 errors left.
> I just started to fix everything while running tests in watch mode, until everything was fixed.

That's awesome. Huge thanks for this!

> If you have more than one JSONInput on the page, it will cause accessibility issues if there is no id provided.

Interesting, we should probably include a test with two inputs in it in the future down the line, so thanks for spotting this!

I'm not merging since I'm waiting for Andrew to give his opinion on such a large change. 
He's rather busy currently so I can't give an estimate to when he'll have the time.

**Comment by PatrickSachs** [comment]
Hey @AndrewRedican - Did you have a chance to take a took at this?

**Comment by AndrewRedican** [comment]
@JustFly1984, thanks for your contribution. Sorry for my late response. I will look at this during the weekend. There are a few items that require urgent attention first regarding potential issues with the latest release.

**Comment by JustFly1984** [comment]
Hey guys is there any movement on this merge request?

**Comment by PatrickSachs** [comment]
Hey @JustFly1984 - I'm not completely sure to be honest. If you want we can merge your PR into a non-master branch on this repo if you want to be able to delete your fork. 

I don't want to merge such a fundamental change to code and tooling into master without the Owners consent.

**Comment by JustFly1984** [comment]
I have read the issues, there was eslint request. I've installed eslint as I use it in my projects. I've carefully refactored the code running tests in background. Does owner against this improvements?

**Comment by PatrickSachs** [comment]
I don't think so. As far as I'm concerned there is no issue with this PR. 

But since Andrew is rather busy at the moment this PR is currently "on hold". I can merge into a **non-mater** branch on this repo for now if you just want to have the branch out of your fork, but I won't merge this PR without his explicit consent since its a rather fundamental change. 
I'll try to contact him this evening via Slack.

**Comment by JustFly1984** [comment]
Hey guys, why is it taking so long?

**Comment by PatrickSachs** [comment]
Hello JustFly.

I've tried contacting Andrew again. I'll wait a few days for a response otherwise I'd consider this project to be unmaintained.

**Comment by JustFly1984** [comment]
Guys is there any movement?

**Comment by PatrickSachs** [comment]
I think that this project can be considered unmaintained, since I am not getting responses on our Slack nor has Andrew been active on GitHub for a decent amount of time. Since Andrew exclusively has publish rights to NPM there isn't a lot I can do.

I'd recommend someone to fork this library and continue to work on it, look for an alternative or wait for the owner to possibly come back one day if it is non mission critical.

I'll merge this branch into /eslint for now so that you can delete your fork if you want to.

I thank you for the time dedicated to this, and am deeply sorry that we cannot provide a satisfactory solution as of now.

**Comment by AndrewRedican** [comment]
@JustFly1984 @PatrickSachs 

I am publishing new release on npm with the latest changes.

**Pull request merged**
